### ISSUE TITLE
Requests should be responded in the same (or less) visibility

### ISSUE THREAD

**Issue by austinhuang0131** [Roboron3042/mastoes-bots#5]
ie. if I DM the bot then it should DM me back, not send it as unlisted...

**Comment by Roboron3042** [comment]
Many people use the "DM" visibility to trigger the bot while hiding the useless mention post from their followers. So the bot is designed to reply in unlisted mode, to allow the poster to share the tree without needing to copy-paste everything.

**Comment by austinhuang0131** [comment]
Yes but what if I don't want others to see the tree...

**Comment by Roboron3042** [comment]
You can reply with #delete and the bot will delete your tree.

**Comment by austinhuang0131** [comment]
fair
